name: 🧑‍💼 Daily Journalist Twitter Analysis (4PM IST Email)

on:
  schedule:
    - cron: '30 10 * * *'  # ⏰ Runs every day at 4:00 PM IST (10:30 UTC)
  workflow_dispatch:

jobs:
  run-daily-journalist-analysis:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      TWITTER_BEARER: ${{ secrets.TWITTER_BEARER }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}
      CC_EMAIL: ${{ secrets.CC_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 📦 Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install yagmail keyring oauth2client
          pip list

      - name: ▶️ Run daily_journalists_twitter_analysis.py
        run: |
          python daily_journalists_twitter_analysis.py
