name: 🐦 Daily Twitter News Analysis (3PM IST Email)

on:
  schedule:
    - cron: '30 09 * * *'  # ⏰ Runs every day at 3:00 PM IST (09:30 UTC)
  workflow_dispatch:       # ✅ Allows manual trigger too

jobs:
  run-daily-twitter-analysis:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      TWITTER_BEARER: ${{ secrets.TWITTER_BEARER }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}
      CC_EMAIL: ${{ secrets.CC_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 📦 Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install yagmail keyring oauth2client
          pip list  # ✅ Log installed packages

      - name: ▶️ Run daily_news_twitter_analysis.py
        run: |
          python daily_news_twitter_analysis.py
